-- Migration to fix tenant_id types (Standardize on INT)
-- Generated by Antigravity on 2026-01-05 00:08
-- DIRECTION: String (slugs) -> Integer (IDs)

-- DISABLE FOREIGN KEYS TEMPORARILY to avoid issues during intermediate updates
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Migrate Data (Slugs to IDs)
-- Update values to generic integers (as strings first, if column is varchar)
-- FAQS
UPDATE faqs SET tenant_id = '1' WHERE tenant_id = 'turp';
UPDATE faqs SET tenant_id = '2' WHERE tenant_id = 'iwrs';
UPDATE faqs SET tenant_id = '3' WHERE tenant_id = 'nipt';
UPDATE faqs SET tenant_id = '4' WHERE tenant_id = 'wes' OR tenant_id = 'westesti';
UPDATE faqs SET tenant_id = '5' WHERE tenant_id = 'trombo' OR tenant_id = 'trombofili';

-- LEGAL DOCUMENTS
UPDATE legal_documents SET tenant_id = '1' WHERE tenant_id = 'turp';
UPDATE legal_documents SET tenant_id = '2' WHERE tenant_id = 'iwrs';
UPDATE legal_documents SET tenant_id = '3' WHERE tenant_id = 'nipt';
UPDATE legal_documents SET tenant_id = '4' WHERE tenant_id = 'wes' OR tenant_id = 'westesti';
UPDATE legal_documents SET tenant_id = '5' WHERE tenant_id = 'trombo' OR tenant_id = 'trombofili';

-- SITE SETTINGS
UPDATE site_settings SET tenant_id = '1' WHERE tenant_id = 'turp';
UPDATE site_settings SET tenant_id = '2' WHERE tenant_id = 'iwrs';
UPDATE site_settings SET tenant_id = '3' WHERE tenant_id = 'nipt';
UPDATE site_settings SET tenant_id = '4' WHERE tenant_id = 'wes' OR tenant_id = 'westesti';
UPDATE site_settings SET tenant_id = '5' WHERE tenant_id = 'trombo' OR tenant_id = 'trombofili';

-- 2. Drop potential conflicting indexes (Prepare for ALTER)
-- FAILURE HANDLED: Index might not exist on target env.
-- DROP INDEX idx_tenant_id ON faqs; 

-- 3. Alter columns to INT
-- This will fail if there are any non-numeric values left (e.g. 'some-other-slug')
ALTER TABLE faqs MODIFY tenant_id INT NOT NULL DEFAULT 1;
ALTER TABLE legal_documents MODIFY tenant_id INT NOT NULL DEFAULT 1;
ALTER TABLE site_settings MODIFY tenant_id INT NOT NULL DEFAULT 1;

-- 4. Add Foreign Keys (Unique Names)
-- Using _v2 suffix to avoid "Duplicate key" error if old metadata persists
ALTER TABLE faqs ADD CONSTRAINT fk_faqs_tenant_id_v2 FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE legal_documents ADD CONSTRAINT fk_legal_documents_tenant_id_v2 FOREIGN KEY (tenant_id) REFERENCES tenants(id);
ALTER TABLE site_settings ADD CONSTRAINT fk_site_settings_tenant_id_v2 FOREIGN KEY (tenant_id) REFERENCES tenants(id);

-- 5. Cleanup
-- Drop redundant column in site_settings if exists
-- ALTER TABLE site_settings DROP COLUMN tenant_id_int;

-- RE-ENABLE FOREIGN KEYS
SET FOREIGN_KEY_CHECKS = 1;
